"""Configuration loader for Bloom.

Resolution order (highest precedence first):
  1. Environment variables (BLOOM_DB_PATH, BLOOM_EMBEDDER, BLOOM_LOG_LEVEL, ...)
  2. ~/.bloom/config.toml
  3. Built-in defaults

Users normally run `bloom-mcp init` once to write config.toml. Env vars are
useful for CI, containers, or per-shell overrides.
"""

from __future__ import annotations

import os
import sys
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

if sys.version_info >= (3, 11):
    import tomllib
else:
    import tomli as tomllib  # type: ignore[no-redef]


def default_home() -> Path:
    """Return the Bloom home directory (~/.bloom by default)."""
    return Path(os.environ.get("BLOOM_HOME") or Path.home() / ".bloom")


def default_db_path() -> Path:
    return default_home() / "loom.db"


def default_config_path() -> Path:
    return default_home() / "config.toml"


@dataclass
class EmbedderConfig:
    provider: str = "none"
    model: str | None = None
    api_key_env: str | None = None


@dataclass
class Config:
    db_path: Path = field(default_factory=default_db_path)
    log_level: str = "INFO"
    embedder: EmbedderConfig = field(default_factory=EmbedderConfig)
    retrieve_top_k: int = 5
    retrieve_max_chars: int = 4000
    snippet_max_chars: int = 600

    @classmethod
    def load(cls, path: Path | None = None) -> "Config":
        cfg_path = path or default_config_path()
        data: dict[str, Any] = {}
        if cfg_path.exists():
            with open(cfg_path, "rb") as fh:
                data = tomllib.load(fh)
        return cls._from_dict(data)

    @classmethod
    def _from_dict(cls, data: dict[str, Any]) -> "Config":
        storage = data.get("storage", {})
        recall = data.get("recall", {})
        embedder = data.get("embedder", {})
        logging_cfg = data.get("logging", {})

        db_path_str = os.environ.get("BLOOM_DB_PATH") or storage.get("db_path")
        db_path = Path(db_path_str).expanduser() if db_path_str else default_db_path()

        log_level = os.environ.get("BLOOM_LOG_LEVEL") or logging_cfg.get("level", "INFO")

        provider = os.environ.get("BLOOM_EMBEDDER") or embedder.get("provider", "none")
        emb = EmbedderConfig(
            provider=provider,
            model=embedder.get("model"),
            api_key_env=embedder.get("api_key_env"),
        )

        return cls(
            db_path=db_path,
            log_level=log_level.upper(),
            embedder=emb,
            retrieve_top_k=int(recall.get("top_k", 5)),
            retrieve_max_chars=int(recall.get("max_chars", 4000)),
            snippet_max_chars=int(recall.get("snippet_max_chars", 600)),
        )

    def write(self, path: Path | None = None) -> Path:
        cfg_path = path or default_config_path()
        cfg_path.parent.mkdir(parents=True, exist_ok=True)
        body = (
            "# Bloom configuration\n"
            "# Generated by `bloom-mcp init`. Edit freely.\n"
            "\n"
            "[storage]\n"
            f'db_path = "{self.db_path}"\n'
            "\n"
            "[recall]\n"
            f"top_k = {self.retrieve_top_k}\n"
            f"max_chars = {self.retrieve_max_chars}\n"
            f"snippet_max_chars = {self.snippet_max_chars}\n"
            "\n"
            "[embedder]\n"
            f'provider = "{self.embedder.provider}"\n'
        )
        if self.embedder.model:
            body += f'model = "{self.embedder.model}"\n'
        if self.embedder.api_key_env:
            body += f'api_key_env = "{self.embedder.api_key_env}"\n'
        body += (
            "\n"
            "[logging]\n"
            f'level = "{self.log_level}"\n'
        )
        cfg_path.write_text(body)
        return cfg_path
